#!/usr/bin/lua
local json = require("luci.json")
local util = require ("luci.util")
require "luci.model.uci"
local uci = luci.model.uci.cursor()
local am = require("andlinkcommon")

local andlk = "andlink"

--log 
local log_file = "/tmp/tzcoapserver.log"
local log_flag = 0 -- nil:don't print log,0:print log to file,1: print log to stdout 
local log_max = 5000 --max line num

function log_info(info)
    if log_flag then
        clean_log()
        if not info then info = " " end 
        if "table" == type(info) then info = json.encode(info) end
        local str_time = os.date("%Y-%m-%d %H:%M:%S",os.time())
        if 0 == log_flag + 0 then
            local lf = io.open(log_file, "a+")
            io.output(lf) 
            io.write(string.format([[%s -->> %s%s]],str_time,string.gsub(info,"\n",""),"\n"))
            io.close(lf)
        else
            print(str_time.." -->> "..info)
        end 
    end 
end

function clean_log()
    if log_file then
        if 0 == os.execute("test -f "..log_file) then
            local function exec(command)
                local pp   = io.popen(command)
                local data = pp:read("*a")
                pp:close()
                return data
            end
            local num = exec("wc -l "..log_file.." 2>&1 | awk \'{print $1}\' ")
            num = tonumber(num) or 1
            if log_max <= num + 0 then
               os.execute("echo -n \' \' > "..log_file)
            end 
        end 
    end 
end
local D = log_info 
--log end

function usage()
print([[usage:andlink-sysupgrade [-u url] [-a ip] [-d delay] 
       -u  url     url of file for download 
       -a  ip      server ip 
       -d  delay   delay download (default:3)
examples:
       andlink-sysupgrade -u http://192.168.1.8/firmware.bin -a 192.168.1.1
       andlink-sysupgrade -u http://192.168.1.8/firmware.bin -a 192.168.1.1 -d 10
       ]])
end

function arg_parse(arg)
local res=nil
local i=1

--if 1 > #arg then
--    usage()
--end

while i <= #arg do
    if "-u" == arg[i] and arg[i+1] and "-" ~= string.sub(arg[i+1],1,1) then
       if not res then res = {} end
       res["url"] = arg[i+1]
       i = i + 1 
    elseif "-a" == arg[i] and arg[i+1] and "-" ~= string.sub(arg[i+1],1,1) then
       if not res then res = {} end
       res["ip"] = arg[i+1]
       i = i + 1 
    elseif "-d" == arg[i] and arg[i+1] and "-" ~= string.sub(arg[i+1],1,1) then
       if not res then res = {} end
       res["delay"] = tonumber(arg[i+1]) or 3
       i = i + 1 
    end 
    i = i + 1 
end
return res
end

--main
local arg_t = arg_parse(arg)
if not arg_t or not arg_t["url"] or not arg_t["ip"] then
   usage() 
   os.exit(1)
end
local delay = tonumber(arg_t["delay"]) or 2
os.execute("sleep "..delay)
D("start download")
uci:load(andlk)
local devid = uci:get(andlk,"andlink","device_id")
local gw = uci:get(andlk,"andlink","gateway")
if not devid or "" == devid or not gw or "" == gw then
    D("device no register,don't download or remote sysupgrade")
end
local d={deviceId=devid,eventType="File"}
local cmd = nil
local res = nil
local dres = am.download(arg_t["url"],"/tmp/")
if 0 == dres then
    d["data"] = {respCode=2000,respCont="File Transfer Complete"}
else
    d["data"] = {respCode=2003,respCont="File Transfer interrupt"}
end
d["timestamp"] = os.time()
cmd = string.format([[coap-client coap://%s/device/inform/data -B 2 -m POST -e '%s']],arg_t["ip"],json.encode(d))
D(cmd)
res = util.exec(cmd)
D(res)
if 0 == dres then
    local filepath = "/tmp/"..am.get_file_name(arg_t["url"])
    D(filepath)
    if not uci:get(andlk,"event") then
        uci:section(andlk,"event","event")
    end
    os.execute(string.format([[sleep 3 && sysupgrade -c %s >/dev/null 2>&1 &]],filepath))
    local sv=util.exec([[cat /etc/openwrt_version | tr -d "\n|\r"]])
    uci:set(andlk,"event","version",sv)
    uci:commit(andlk)
end
