#!/bin/sh





#to ensure the ubus is working well  
/sbin/2060 &

/usr/bin/lua /sbin/testubus.lua &


test -f /sbin/shengji && /sbin/shengji &

proto=`pidof check |wc -l`
if [ "$proto" = "0" ]; then
               /sbin/check &
fi

