#!/bin/sh




if [ $1 = "on" ];then

        echo  1 > /sys/class/leds/wifi/brightness 
	echo  1 > /sys/class/leds/power/brightness
elif [ $1 = "off" ]
then

        echo  0 > /sys/class/leds/wifi/brightness
        echo  0 > /sys/class/leds/power/brightness  	
fi



