#!/bin/sh



i=0

while [ $i -lt 10 ]
do

	result=`cat /tmp/resetbutton`
	#echo $result
	#echo "zz"
	if [ $result = "reset" ];then
	echo "pass"
	rm /tmp/resetbutton
	break
	fi
	sleep 1
	i=$(($i+1))

done






