#!/bin/sh




i=0

while [ $i -lt 4 ]
do





        flag=`uci get wireless.@wifi-iface[$i].mode`
 

        if [ "$flag" == "sta" ];then
        
	break
        fi


        i=$(($i+1))
echo "xx"
done


 if [ "$flag" == "sta" ];then 

                 uci set dhcp.lan.ignore=1   
		 uci commit
        else                                    
                uci set dhcp.lan.ignore=0       
               uci commit                                 
fi                                      
	
