#!/bin/sh



iptables -t nat -F PREROUTING



#iptables -D WiFiDog_br-lan_Unknown -m physdev --physdev-in ra0   -j DROP
#iptables -D WiFiDog_br-lan_Unknown -m physdev --physdev-in ra1   -j DROP
#iptables -D WiFiDog_br-lan_Unknown -m physdev --physdev-in ra2   -j DROP
#iptables -D WiFiDog_br-lan_Unknown -m physdev --physdev-in ra3   -j DROP


if [ "$1" != "off" ];then

i=0

while [ $i -lt 4 ]
do

	flag=`uci get wireless.@wifi-iface[$i].portal`
	echo $flag
	
	if [ "$flag" == "1" ];then
		echo "write rule to prerouting of nat"

#	        iptables -D WiFiDog_br-lan_Unknown -m physdev --physdev-in ra$i  -j DROP          
#                iptables -A WiFiDog_br-lan_Unknown -m physdev --physdev-in ra$i   -j DROP  
		iptables -t nat -A PREROUTING -m physdev --physdev-in ra$i -j WiFiDog_br-lan_Outgoing
	fi	
		

	i=$(($i+1))
done


fi

iptables -t nat -A PREROUTING -j delegate_prerouting






